### ISSUE TITLE
Forge-generated hosts get in the way of local playbooks

### ISSUE THREAD

**Issue by JScott** [colstrom/forge#3]
If I have a system that runs Ansible playbooks on localhost, the Forge-generated `/etc/ansible/hosts` will include the group_vars that are vault-protected. I shouldn't know about this vault with my scripts and thus have to work around it.

This an overreaching of Forge's domain. It shouldn't clobber my existing playbooks.

**Comment by colstrom** [comment]
After some observation of Forge in production deployments, this doesn't seem to cause conflicts, unless you're running ad-hoc playbooks against a Forged system.
